### PR TITLE
Add test for remove( ) and bulkInsert( )

### PR DESCRIPTION
**Pull request by JSAssassin**
addresses #12

### CODE REVIEW

**Comment by mattcollier** [comment]
@JSAssassin this needs to be rebased.

**Review by aljones15 — APPROVED** [review]
Good work here. Also I like the fruit themed resource names. If we can rename things like `result2` and `result3` to more meaningful names that would help alot and make the tests more readable.

**Review by dmitrizagidulin — APPROVED** [review]
👍 
Thanks!

**Review by dlongley — APPROVED** [review]
Thanks!

**Pull request merged**
